CREATE TABLE IF NOT EXISTS KALAHA (
  ID INT PRIMARY KEY,
  CURRENT_PLAYER INT,
  STATUS INT,
  PIT_COUNT INT,
  WINNER INT,
  PLAYER1_LAST_PIT_INDEX INT,
  PLAYER2_FIRST_PIT_INDEX INT,
  PLAYER2_LAST_PIT_INDEX INT,
  CREATED_DATE TIMESTAMP,
  UPDATED_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS KALAHA_PIT (
  ID INT,
  STONES INT,
  GAME_ID INT,
  CONSTRAINT FK_GAME_ID FOREIGN KEY (GAME_ID) REFERENCES KALAHA(ID)
);


CREATE SEQUENCE SEQ_KALAH_GAME
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1;