CREATE TABLE IF NOT EXISTS KALAHA (
  ID INT PRIMARY KEY,
  CURRENT_PLAYER INT,
  STATUS INT,
  PIT_COUNT INT,
  WINNER INT,
  STONES_PER_PIT INT,
  CREATED_DATE TIMESTAMP,
  UPDATED_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS KALAHA_PIT (
  ID INT,
  STONES INT,
  GAME_ID INT,
  CONSTRAINT FK_GAME_ID FOREIGN KEY (GAME_ID) REFERENCES KALAHA(ID)
);